### ISSUE TITLE
Invalid resource handle (CUDA_ERROR_INVALID_HANDLE)

### ISSUE THREAD

**Issue by ghost** [m4rs-mt/ILGPU#60]
Hi @m4rs-mt,

i try to run ILGPU (0.7.0) combined with ML.NET (Tensorflow.GPU).
Both separate are working correctly.

If i create a ILGPU context and load all my kernels and after that create a ML context it seems that ILGPU loses it's access to the GPU.

If i create the ML context first and after that the ILGPU context, everything is working.
Is there any way/workaround so that ILGPU keeps it access to the GPU?

**Comment by m4rs-mt** [comment]
@LTOctum thanks for the submission of this issue. Unfortunately I have no insight into ML.NET, nor into its GPU handling. Can you provide simplified example program so that I can try to dive into it?

**Comment by LTOctum** [comment]
Hi @m4rs-mt,
attached a quick and dirty sample showing the problem.
[ILGPU_MLNET.zip](https://github.com/m4rs-mt/ILGPU/files/4133741/ILGPU_MLNET.zip)

**Comment by m4rs-mt** [comment]
I have analyzed the samples you provided. It turns out that all ILGPU handles remain the same and are still "valid". But I was able to reproduce your problem on a GeForce GTX 1080TI with driver version 440.XX and below. An upgrade of the driver to 441.87 solved all problems for me.

Summary: Instantiating the ML.Net context does not affect internal ILGPU pointers. Instead, they somehow seem to be invalid within the driver for some reason.

**Comment by LTOctum** [comment]
Thanks for the investigation @m4rs-mt.
I will try the solution on my side and let you know.

**Comment by LTOctum** [comment]
Too bad, for the Quadro M2200 is only 441.66 out.
I have to wait for Nvidia to provide a new version.

**Comment by m4rs-mt** [comment]
@LTOctum I'm not sure if the problem "disappears" when you update your graphics driver. Maybe we can find another way to investigate this problem?

**Comment by m4rs-mt** [comment]
I will close this issue for the time being. If the problem arises at a particular time, we can easily return to this ticket.
